//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms_netService.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wekrmpc15.am.gdynia.pl/www/serwis/", ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wekrmpc15.am.gdynia.pl/www/serwis/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wekrmpc15.am.gdynia.pl/www/serwis/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wekrmpc15.am.gdynia.pl/www/serwis/seyHello", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string seyHello(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wekrmpc15.am.gdynia.pl/www/serwis/seyHello", ReplyAction="*")]
        System.Threading.Tasks.Task<string> seyHelloAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wekrmpc15.am.gdynia.pl/www/serwis/dodawanie", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double dodawanie(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wekrmpc15.am.gdynia.pl/www/serwis/dodawanie", ReplyAction="*")]
        System.Threading.Tasks.Task<double> dodawanieAsync(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wekrmpc15.am.gdynia.pl/www/serwis/listaDostawcow", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable listaDostawcow();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wekrmpc15.am.gdynia.pl/www/serwis/listaDostawcow", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> listaDostawcowAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wekrmpc15.am.gdynia.pl/www/serwis/studenci", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable studenci();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wekrmpc15.am.gdynia.pl/www/serwis/studenci", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> studenciAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wekrmpc15.am.gdynia.pl/www/serwis/aktualizacja", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int aktualizacja(System.Data.DataTable tabela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wekrmpc15.am.gdynia.pl/www/serwis/aktualizacja", ReplyAction="*")]
        System.Threading.Tasks.Task<int> aktualizacjaAsync(System.Data.DataTable tabela);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : WindowsForms_netService.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<WindowsForms_netService.ServiceReference1.ServiceSoap>, WindowsForms_netService.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string seyHello(string name) {
            return base.Channel.seyHello(name);
        }
        
        public System.Threading.Tasks.Task<string> seyHelloAsync(string name) {
            return base.Channel.seyHelloAsync(name);
        }
        
        public double dodawanie(double x, double y) {
            return base.Channel.dodawanie(x, y);
        }
        
        public System.Threading.Tasks.Task<double> dodawanieAsync(double x, double y) {
            return base.Channel.dodawanieAsync(x, y);
        }
        
        public System.Data.DataTable listaDostawcow() {
            return base.Channel.listaDostawcow();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> listaDostawcowAsync() {
            return base.Channel.listaDostawcowAsync();
        }
        
        public System.Data.DataTable studenci() {
            return base.Channel.studenci();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> studenciAsync() {
            return base.Channel.studenciAsync();
        }
        
        public int aktualizacja(System.Data.DataTable tabela) {
            return base.Channel.aktualizacja(tabela);
        }
        
        public System.Threading.Tasks.Task<int> aktualizacjaAsync(System.Data.DataTable tabela) {
            return base.Channel.aktualizacjaAsync(tabela);
        }
    }
}
